apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-archive
  labels:
    app: docker-archive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-archive
  template:
    metadata:
      labels:
        app: docker-archive
    spec:
      containers:
      - name: registry
        image: registry:2.7.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: docker-registry-storage
      - name: sync
        image: tmaxcloudck/gsheet-sync:dev
        imagePullPolicy: Always
        env:
          - name: SHEET_URL
            value: https://docs.google.com/spreadsheets/d/1_KVOzzVlAl8VQ6y6I4y2NnsokjF-yE51uOXcZPyzDEU/edit#gid=0
          - name: SHEET_IDX
            value: 0
          - name: COL_NUM
            value: 1
          - name: ROW_FROM
            value: 2
          - name: REGISTRY_URL
            value: localhost:5000
          - name: DOCKER_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: dockerio
          - name: QUAY_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: quayio
          - name: GCR_CRED
            valueFrom:
              secretKeyRef:
                name: regcred
                key: gcr
          - name: REPORT_PATH
            value: /data
          - name: NOTIFY_URL
            value: http://localhost:3000/run
        ports:
          - containerPort: 8080
      - name: exporter
        image: tmaxcloudck/regarchiver:dev
        imagePullPolicy: Always
        env:
          - name: TAR_PATH
            value: /data
          - name: UPLOAD_SCP_PATH
            value: ck-ftp@192.168.1.150:/home/ck-ftp/k8s/install/offline/supercloud-images
          - name: UPLOAD_SCP_PASS
            value: ck-ftp
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /data
            name: docker-registry-storage
      volumes:
      - name: docker-registry-storage
        persistentVolumeClaim:
          claimName: docker-registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docker-archive
spec:
  type: NodePort
  selector:
    app: docker-archive
  ports:
    - name: docker
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30800
      targetPort: 8080
    - name: exporter
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
