
DOCKERCMD=$(shell which docker)
DOCKERBUILD=$(DOCKERCMD) build

IMAGENAME=regarchiver
VERSIONTAG=dev

SOURCE_PATH=/tmp/vol1
DESTINATION_PATH=/tmp/vol2
DOCKER_REG_VOLUME_PATH=src
STATIC_SRV_VOLUME_PATH=/dst

build:
	@echo "building..."
	@$(DOCKERBUILD) . -t $(IMAGENAME):$(VERSIONTAG)
